# Generated by Django 2.2.7 on 2019-11-21 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 7, 54, 9, 690431)),
        ),
    ]
