# Generated by Django 2.2.7 on 2019-11-23 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20191121_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 7, 7, 35, 549364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 23, 7, 7, 35, 551724, tzinfo=utc), null=True, verbose_name='Date article published'),
        ),
    ]
