# Generated by Django 2.2.7 on 2019-11-23 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20191123_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 13, 32, 43, 467655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 23, 13, 32, 43, 471437, tzinfo=utc), null=True, verbose_name='Date article published'),
        ),
    ]
