# Generated by Django 2.2.7 on 2019-12-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20191130_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.CharField(db_index=True, editable=False, max_length=40)),
                ('session', models.CharField(db_index=True, editable=False, max_length=40)),
                ('user_agent', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HitCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('hits24h', models.PositiveIntegerField(default=0)),
                ('hits4h', models.PositiveIntegerField(default=0)),
                ('hits4h_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='postpage',
            options={'ordering': ['-date_published']},
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='hits',
        ),
        migrations.AlterField(
            model_name='postpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page', max_length=511),
        ),
        migrations.AddIndex(
            model_name='postpage',
            index=models.Index(fields=['date_published'], name='front_postp_date_pu_e274f0_idx'),
        ),
        migrations.AddField(
            model_name='hitcounter',
            name='home',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='front.HomePage'),
        ),
        migrations.AddField(
            model_name='hitcounter',
            name='post',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='front.PostPage'),
        ),
        migrations.AddField(
            model_name='hit',
            name='hit_counter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hit_object', to='front.HitCounter'),
        ),
    ]
