# Generated by Django 2.2.7 on 2019-12-07 10:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('front', '0008_auto_20191202_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.core.fields.RichTextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=31, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='bottom_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Bottom Ad script'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='left_top_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Left Top Ad script'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='list_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='List Ad script'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='news_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='News Ad script'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='top_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Top Ad script'),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_index', to='editorial.People'),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='front.ContactPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
