# Generated by Django 2.2.7 on 2020-01-07 13:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('front', '0009_auto_20191207_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsettings',
            name='left_bottom_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Left Bottom Ad script'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='news_bottom1_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='news_bottom1_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='News Buttom1 Ad script'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='news_bottom1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='news_bottom2_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='news_bottom2_script',
            field=wagtail.core.fields.StreamField([('rawScript', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='News Buttom2 Ad script'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='news_bottom2_url',
            field=models.URLField(blank=True),
        ),
    ]
