# Generated by Django 2.2.7 on 2019-11-30 12:55

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='people',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['old_id'], name='editorial_p_old_id_664ad7_idx'),
        ),
    ]
