# Generated by Django 2.2.7 on 2019-12-07 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editorial', '0002_auto_20191130_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_object', to=settings.AUTH_USER_MODEL),
        ),
    ]
